# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: -2.57
  joint_a2: 1.30
  joint_a3: -1.92
  joint_a4: 1.50
  joint_a5: -1.50
  joint_a6: 1.95
  joint_a7: 1.35